Cscfa\Bundle\CSManager\CoreBundle\Entity\Navbar:
    properties:
        id:
            - Uuid: 
                message:          core.form.navbar.validation.id
        name:
            - NotBlank: 
                message:          core.form.navbar.validation.name.notblank
            - Regex:
                pattern:          '/ /'
                match:            false
                message:          core.form.navbar.validation.name.regex
        route:
            - NotBlank: 
                message:          core.form.navbar.validation.route.notblank
            - Regex:
                pattern:          '/ /'
                match:            false
                message:          core.form.navbar.validation.route.regex
        translation:
            - NotBlank: 
                message:          core.form.navbar.validation.translation.notblank
        priority:
            - NotBlank: 
                message:          core.form.navbar.validation.priority.notblank
            - Range:
                min:              0
                minMessage:       core.form.navbar.validation.priority.range.min
                invalidMessage:   core.form.navbar.validation.priority.range.invalid
            - Type:
                type:             integer
              message:            core.form.navbar.validation.priority.type