
#cscfa_cs_manager_config:
#    resource: "@CscfaCSManagerConfigBundle/Resources/config/routing.yml"
#    prefix:   /

#cscfa_cs_manager_user:
#    resource: "@CscfaCSManagerUserBundle/Resources/config/routing.yml"
#    prefix:   /

#cscfa_cs_manager_task:
#    resource: "@CscfaCSManagerTaskBundle/Resources/config/routing.yml"
#    prefix:   /

#cscfa_cs_manager_project:
#    resource: "@CscfaCSManagerProjectBundle/Resources/config/routing.yml"
#    prefix:   /

#cscfa_cs_manager_dashboard:
#    resource: "@CscfaCSManagerDashboardBundle/Resources/config/routing.yml"
#    prefix:   /

#cscfa_cs_manager_core:
#    resource: "@CscfaCSManagerCoreBundle/Resources/config/routing.yml"
#    prefix:   /
    
cscfa_core:
    resource: "@CscfaSecurityBundle/Resources/config/routing.yml"
    prefix:   /
