forgot_password:
    path:     /forgotPassword
    defaults: { _controller: "CscfaCSManagerSecurityBundle:Security:forgot" }
    methods:  [GET|POST]
login_check:
    path:     /login_check
    defaults: { _controller: "CscfaCSManagerCoreBundle:Security:loginCheck" }
    methods:  [POST]
logout:
    path:     /logout
    defaults: { _controller: "CscfaCSManagerSecurityBundle:Security:logout" }
    methods:  [GET]
register:
    path:     /register
    defaults: { _controller: "CscfaCSManagerSecurityBundle:Security:register" }
    methods:  [POST]
mail_confirm:
    path:     /account/validate/{user}/{confirmationToken}
    defaults: { _controller: "CscfaCSManagerSecurityBundle:Security:confirmationByMail" }
    methods:  [GET]




security_css_headerConnecting:
    path:     /css/{media}/securityHeaderConnecting.css
    defaults: { _controller: "CscfaCSManagerSecurityBundle:CSS:headerConnecting", media: "screen" }
    methods:  [GET]
    requirements:
        media:  screen|handheld|print|aural|speech|braille|embossed|projection|tty|tv|all
security_css_forgot:
    path:     /css/{media}/securityForgot.css
    defaults: { _controller: "CscfaCSManagerSecurityBundle:CSS:forgot", media: "screen" }
    methods:  [GET]
    requirements:
        media:  screen|handheld|print|aural|speech|braille|embossed|projection|tty|tv|all
security_css_register:
    path:     /css/{media}/securityRegister.css
    defaults: { _controller: "CscfaCSManagerSecurityBundle:CSS:register", media: "screen" }
    methods:  [GET]
    requirements:
        media:  screen|handheld|print|aural|speech|braille|embossed|projection|tty|tv|all
