services:
    csmanager.security_form.signin:
        class: Cscfa\Bundle\CSManager\SecurityBundle\Objects\singin\SignInType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags: 
            - { name: form.type, alias: signin }
